# Generated by Django 5.0.2 on 2024-05-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIDS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='description',
        ),
    ]
